services:
  browser:
    image: ghcr.io/go-rod/rod:latest
    hostname: browser
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - browserBroNetwork
  api:
    build: .
    environment:
      GET_HOSTS_FROM: dns
      BROWSERBRO_BROWSER_SERVICE_URL: ws://browser:7317
    ports:
      - 10001:10001
      - 8889:8889
    depends_on:
      - browser
    networks:
      - browserBroNetwork

networks:
  browserBroNetwork:
    driver: "bridge"